### ISSUE TITLE
设置图片大小后报错

### ISSUE THREAD

**Issue by Jelly0726** [chaychan/BottomBarLayout#2]
Caused by: java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams
                                                                                  at com.chaychan.library.BottomBarItem.init(BottomBarItem.java:128)
                                                                                  at com.chaychan.library.BottomBarItem.<init>(BottomBarItem.java:88)
                                                                                  at com.chaychan.library.BottomBarItem.<init>(BottomBarItem.java:54)

将
if (mIconWidth != 0 && mIconHeight != 0){
            //如果有设置图标的宽度和高度，则设置ImageView的宽高
            LayoutParams imageLayoutParams = (LayoutParams) mImageView.getLayoutParams();
            imageLayoutParams.width = mIconWidth;
            imageLayoutParams.height = mIconHeight;
            mImageView.setLayoutParams(imageLayoutParams);
        }
修改为可解决：
if (mIconWidth != 0 && mIconHeight != 0){
            //如果有设置图标的宽度和高度，则设置ImageView的宽高
            FrameLayout.LayoutParams imageLayoutParams = (FrameLayout.LayoutParams) mImageView.getLayoutParams();
            imageLayoutParams.width = mIconWidth;
            imageLayoutParams.height = mIconHeight;
            mImageView.setLayoutParams(imageLayoutParams);
        }

**Comment by chaychan** [comment]
@Jelly0726 多谢你的反馈，现在已经修复。
