### ISSUE TITLE
问题非常大，java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by hdProj** [chaychan/BottomBarLayout#53]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.chaychan.library.BottomBarLayout.onRestoreInstanceState(BottomBarLayout.java:272)
	at android.view.View.dispatchRestoreInstanceState(View.java:20929)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4019)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4025)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4025)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4025)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4025)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4025)
	at android.view.View.restoreHierarchyState(View.java:20907)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2185)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1721)

**Comment by chaychan** [comment]
@hedongBlog 请用最新版2.0.2
